name: Pre-release workflow
run-name: Pre-release workflow for PR number ${{ inputs.pr_number }}
permissions:
  contents: write
on:
  workflow_call:
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Pre-release generation
        env:
          ref_name: ${{ github.head_ref }}
          pr_number: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i s/'branch_name'/"${ref_name}"/ .releaserc
          sed -i s/'pr_number'/"PR${pr_number}"/ .releaserc
          echo 'hola' > ever.txt
          npm install -g semantic-release
          npx semantic-release --debug

