name: Pre-release workflow
run-name: Pre-release workflow for PR number ${{ inputs.pr_number }}
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      pr_number:
        type: number
        required: true
        description: PR number
      commit_sha:
        type: string
        required: true
        description: Commit sha of merge candidate branch
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.commit_sha }}
      - name: Pre-release generation
        env:
          ref_name: ${{ github.ref_name }}
          pr_number: ${{ inputs.pr_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i s/'branch_name'/"${ref_name}"/ .releaserc
          sed -i s/'pr_number'/"PR${pr_number}"/ .releaserc
          echo 'hola' > ever.txt
          npm install -g semantic-release
          npx semantic-release --debug

