name: Release workflow
run-name: Release workflow
permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
jobs:
  release:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release generation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_name == 'main' && github.event_name == 'push'
        run: |
          npm install -g semantic-release
          npx semantic-release --debug
      - name: Pre-release branch generation and manual workflow execution
        env:
          pr_number: ${{ github.event.number }}
          head_ref: ${{ github.head_ref }}
          commit_sha: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: false && github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          gh workflow run prerelease.yml --ref "${head_ref}" -f pr_number="${pr_number}" -f commit_sha="${commit_sha}"
  prerelease:
    uses: ./.github/workflows/prerelease2.yml
    if: github.event_name == 'pull_request' && github.base_ref == 'main'