name: Release workflow
run-name: Release workflow
permissions:
  contents: write
  issues: write
  pull-requests: write
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release generation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_name == 'main' && github.event_name == 'push'
        run: |
          npm install -g semantic-release
          npx semantic-release --debug
      - name: Pre-release branch generation and manual workflow execution
        env:
          pr_number: ${github.event.number}
          tmp_branch: tmp-PR${{ github.event.number }}-${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout "${head_ref}"
          git checkout -b "${tmp_branch}"
          git merge main
          git push origin "${tmp_branch}" -u
          gh workflow run prerelease.yml --ref "${tmp_branch}" -f pr_number="${pr_number}"





